sudo: required

language: cpp

env:
  matrix:
    # what are the realistic things we want to test against?
    # C/C++ compiler versions:
      # gcc: 447, 485, 492, 531, 631, 64X, 71X, 721?
      # clang: 32, 34, 35, 36, 37, 38, 39, 4, 5, 6, 7?
      # libc++ vs libstdc++
      # c++11, c++14, c++17, etc
    # Python versions
      # 27, 33, 34, 35, 36, pypy27, pypy32, pypy35?
    # needed vars:
      # PYTHON_VERSON
      # CLANG_VERSON
      # GCC_VERSON
      # COMPILER = CLANG/GCC
    - OS_TYPE=centos OS_VERSION=6 DOCKER_IMAGE=gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker:slc6
    - OS_TYPE=centos OS_VERSION=7 DOCKER_IMAGE=gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker:cc7
    # - OS_TYPE=centos OS_VERSION=8 DOCKER_IMAGE=gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker:cc8
    # - OS_TYPE=centos OS_VERSION=6 DOCKER_IMAGE=cern/slc6-base
    # - OS_TYPE=centos OS_VERSION=7 DOCKER_IMAGE=cern/cc7-base

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 2
  - docker pull $DOCKER_IMAGE
  - docker ps -al
  ## Uncomment in the future for potential deployment tasks
  ## Thanks to: https://djw8605.github.io/2017/02/08/deploying-docs-on-github-with-travisci/
  # - openssl aes-256-cbc -K $encrypted_8a96a0c3dc4a_key -iv $encrypted_8a96a0c3dc4a_iv -in .travis/cmsgemos-deploy-key.enc -out ~\/.ssh/cmsgemos-deploy-key -d
  # - chmod 600 deploy-key
  # - eval `ssh-agent -s`
  # - ssh-add deploy-key

# stages:
#   - compile
#   - test
#   - name: buildrpms
#   - name: release
#     if: branch = master
#     tags: true
#   - name: deploy
#     if: branch = master

# before_release:
#   # Set up git user name and tag this commit
#   - git config --local user.name "YOUR GIT USER NAME"
#   - git config --local user.email "YOUR GIT USER EMAIL"
#   ?create the changelog
#   ?update release notes
#   ?run our cmsgemostag script instead?
#   Sign the tags
#   - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

# release:
#   # deploy to Github releases
#   provider: releases
#   api_key:
#     secure: "GITHUB OAUTH TOKEN"
#   file_glob: true
#   file:
#     - *.tbz2
#     - *.tgz
#     - *.rpm
#     - README.md
#     - CHANGELOG.md
#     - docs
#   prerelease: true
#   skip_cleanup: true
#   on:
#     tags: true

script:
 - ./.travis/travis.sh ${OS_VERSION}
# - ./.travis/travis.sh ${OS_VERSION}

after_success:
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
